name: 'supabase_analytics'
version: '1.0.0'
config-version: 2

profile: 'supabase_profile'

model-paths: ["models"]


models:
  supabase_analytics:
    bronze:
      +materialized: incremental
      +schema: bronze