name: dbt run

on:
  repository_dispatch:
    types: [storage_file_uploaded]

  workflow_dispatch:
    inputs:
      manual_date:
        description: 'Fecha a procesar manualmente (formato: YYYY-MM-DD)'
        required: true
        default: '2026-07-18'

jobs:
  run-dbt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install dbt-core dbt-mysql

      - name: Execute dbt for the Specific Date Partition
        env:
          DBT_ENV_SECRET_PASSWORD: ${{ secrets.DBT_DB_PASSWORD }}
        run: |
          # Capturar los parámetros según el origen del evento
          IF_SUPABASE="${{ github.event.client_payload.execution_date }}"
          IF_MANUAL="${{ github.event.inputs.manual_date }}"
          
          # Priorizar la fecha del Webhook; si está vacía, usar la del input manual
          TARGET_DATE=${IF_SUPABASE:-$IF_MANUAL}
          
          echo "Fecha final seleccionada para el procesamiento: $TARGET_DATE"
          
          # CORRECCIÓN: --profiles-dir . apunta al directorio actual donde está tu profiles.yml
          dbt run --select path.to.your.bronze.model --profiles-dir . --vars "{'target_date': '$TARGET_DATE'}"